library("sqldf")
df<- read.csv.sql("household_power_consumption.txt", sql = " select * from file where Date='1/2/2007' or Date='2/2/2007'", header=TRUE, sep=';')
df$realtime <- as.POSIXct(strptime(paste(df$Date, df$Time),format = "%d/%m/%Y %H:%M:%S"),tz = "")
png(filename = "plot4.png",height = 480, width = 480)
par(mfcol=c(2,2))
with(df,{
  plot(df$realtime,df$Global_active_power,type = "n", ylab = "Global Active Power (kilowatts)", xlab="")
  lines(df$realtime,df$Global_active_power)
  plot(df$realtime,df$Sub_metering_1,type = "n", ylab = "Energy sub metering", xlab="")
  lines(df$realtime,df$Sub_metering_1,col="black")
  lines(df$realtime,df$Sub_metering_2,col="red")
  lines(df$realtime,df$Sub_metering_3,col="blue")
  legend("topright",lty = c(1,1,1),col = c("black", "red", "blue"), legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
  plot(df$realtime,df$Voltage,type = "n", ylab = "Voltage", xlab = "Datetime")
  lines(df$realtime,df$Voltage)
  plot(df$realtime,df$Global_reactive_power,type = "n", ylab = "Global_reactive_power",xlab = "Datetime")
  lines(df$realtime,df$Global_reactive_power)
})
dev.off()
